In [10]:
import matplotlib.pyplot as plot
import pandas as pd
import numpy as np

co_2018_df = pd.read_csv("CO_2018.csv")
co_2019_df = pd.read_csv("CO_2018.csv")
co_2020_df = pd.read_csv("CO_2018.csv")
no2_2018_df = pd.read_csv("NO2_2018.csv")
no2_2019_df = pd.read_csv("NO2_2019.csv")
no2_2020_df = pd.read_csv("NO2_2020.csv")
pm25_2018_df = pd.read_csv("PM2.5_2018.csv")
pm25_2019_df = pd.read_csv("PM2.5_2019.csv")
pm25_2020_df = pd.read_csv("PM2.5_2020.csv")
# pollutants = ["co","no2","pm25"]
# for pollutant in pollutants:
#     f"{pollutant}_append_df" = f"{pollutant}_2018_df".append([f"{pollutant}_2019_df",f"{pollutant}_2020_df"])
co_append_df = co_2018_df.append([co_2019_df,co_2020_df])
co_append_df = co_append_df.rename(columns={"AQS_PARAMETER_DESC":"POLLUTANT"})
co_append_df["ABBREVIATION"] = "CO"
co

no2_append_df = co_2018_df.append([no2_2019_df,no2_2020_df])
pm25_append_df = pm25_2018_df.append([pm25_2019_df,pm25_2020_df])
co_append_df

# co_append_df["DATE"] = [a.split("/")[0] for a in traffic_df["TIME"]]
# # traffic_df["DATE"] = [(a.split("/")[0]+"/"+a.split("/")[1]) for a in traffic_df["date"]]
# traffic_df["DAY"] = [a.split("/")[1] for a in traffic_df["DATE"]]
# traffic_df["YEAR"] = [a.split("/")[2] for a in traffic_df["DATE"]]

,Date,Source,Site ID,POC,Daily Max 8-hour CO Concentration,UNITS,DAILY_AQI_VALUE,Site Name,DAILY_OBS_COUNT,PERCENT_COMPLETE,...,POLLUTANT,CBSA_CODE,CBSA_NAME,STATE_CODE,STATE,COUNTY_CODE,COUNTY,SITE_LATITUDE,SITE_LONGITUDE,ABBREVIATION
0,01/01/2018,AQS,170314201,1,0.5,ppm,6,NORTHBROOK WATER PLANT,19,79.0,...,Carbon monoxide,16980,"Chicago-Naperville-Elgin, IL-IN-WI",17,Illinois,31,Cook,42.139996,-87.799227,CO
1,01/02/2018,AQS,170314201,1,0.4,ppm,5,NORTHBROOK WATER PLANT,24,100.0,...,Carbon monoxide,16980,"Chicago-Naperville-Elgin, IL-IN-WI",17,Illinois,31,Cook,42.139996,-87.799227,CO
2,01/03/2018,AQS,170314201,1,0.6,ppm,7,NORTHBROOK WATER PLANT,24,100.0,...,Carbon monoxide,16980,"Chicago-Naperville-Elgin, IL-IN-WI",17,Illinois,31,Cook,42.139996,-87.799227,CO
3,01/04/2018,AQS,170314201,1,0.6,ppm,7,NORTHBROOK WATER PLANT,24,100.0,...,Carbon monoxide,16980,"Chicago-Naperville-Elgin, IL-IN-WI",17,Illinois,31,Cook,42.139996,-87.799227,CO
4,01/05/2018,AQS,170314201,1,0.7,ppm,8,NORTHBROOK WATER PLANT,24,100.0,...,Carbon monoxide,16980,"Chicago-Naperville-Elgin, IL-IN-WI",17,Illinois,31,Cook,42.139996,-87.799227,CO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340,12/27/2018,AQS,170314201,1,0.2,ppm,2,NORTHBROOK WATER PLANT,24,100.0,...,Carbon monoxide,16980,"Chicago-Naperville-Elgin, IL-IN-WI",17,Illinois,31,Cook,42.139996,-87.799227,CO
341,12/28/2018,AQS,170314201,1,0.2,ppm,2,NORTHBROOK WATER PLANT,24,100.0,...,Carbon monoxide,16980,"Chicago-Naperville-Elgin, IL-IN-WI",17,Illinois,31,Cook,42.139996,-87.799227,CO
342,12/29/2018,AQS,170314201,1,0.2,ppm,2,NORTHBROOK WATER PLANT,24,100.0,...,Carbon monoxide,16980,"Chicago-Naperville-Elgin, IL-IN-WI",17,Illinois,31,Cook,42.139996,-87.799227,CO
343,12/30/2018,AQS,170314201,1,0.2,ppm,2,NORTHBROOK WATER PLANT,24,100.0,...,Carbon monoxide,16980,"Chicago-Naperville-Elgin, IL-IN-WI",17,Illinois,31,Cook,42.139996,-87.799227,CO
344,12/31/2018,AQS,170314201,1,0.3,ppm,3,NORTHBROOK WATER PLANT,24,100.0,...,Carbon monoxide,16980,"Chicago-Naperville-Elgin, IL-IN-WI",17,Illinois,31,Cook,42.139996,-87.799227,CO

In [6]:
no2_append_df

In [6]:
pm25_append_df